%% This code is aim to initialize the USRP transmitter and receiver 
function [radio_Tx,radio_Rx] = USRP_init(rx_length)
    %TX_RX_INIT Summary of this function goes here
    %   Detailed explanation goes here
    platform = "N200/N210/USRP2";
    address  = '192.168.10.2';
    USRPGain            = 5;  % Set USRP radio gain
    USRPCenterFrequency = 915*1e6;  % Set USRP radio center frequency
    
    radio_Tx = comm.SDRuTransmitter(...
                        'Platform',             platform, ...
                        'IPAddress',            address, ...
                        'CenterFrequency',      USRPCenterFrequency, ...
                        'Gain',                 USRPGain);
    
    radio_Rx = comm.SDRuReceiver(...
                    'Platform',             platform, ...
                    'IPAddress',            address, ...
                    'CenterFrequency',      USRPCenterFrequency, ...
                    'Gain',                 5, ...
                    'SamplesPerFrame',      rx_length, ...
                    'OutputDataType',       'double') ; 
                   
end
